server.port=${SERVER_PORT:${PORT:8080}}

spring.datasource.url=${DB_URL:jdbc:mysql://switchback.proxy.rlwy.net:16428/railway?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:tGEWgxzdQaMxtkLxZLoJoLthRsEtfIwD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false

app.jwt.secret=${JWT_SECRET:VGhpc0lzQVN1dmlkaGFFbGl0ZVNlY3JldEtleVRoYXROZWVkc0F0TGVhc3QzMkNoYXJz}
app.jwt.expiration=${JWT_EXPIRATION:900000}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
